취소되지 않은 진료 예약 조회하기
PATIENT, DOCTOR 그리고 APPOINTMENT 테이블에서 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성해주세요. 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목이 출력되도록 작성해주세요. 결과는 진료예약일시를 기준으로 오름차순 정렬해주세요.

--MYSQL
SELECT BC.APNT_NO, A.PT_NAME, A.PT_NO, BC.MCDP_CD, BC.DR_NAME, BC.APNT_YMD
FROM (SELECT C.PT_NO, C.MCDP_CD, C.APNT_YMD, B.DR_NAME, C.APNT_NO
      FROM DOCTOR B
      JOIN APPOINTMENT C
      ON B.DR_ID = C.MDDR_ID
      WHERE DATE_FORMAT(C.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
      AND C.MCDP_CD = 'CS'
      AND C.APNT_CNCL_YN = 'N') BC
JOIN PATIENT A
ON A.PT_NO = BC.PT_NO
ORDER BY BC.APNT_YMD ASC;

--ORACLE
SELECT BC.APNT_NO, A.PT_NAME, A.PT_NO, BC.MCDP_CD, BC.DR_NAME, BC.APNT_YMD
FROM (SELECT C.PT_NO, C.MCDP_CD, C.APNT_YMD, B.DR_NAME, C.APNT_NO
      FROM DOCTOR B
      JOIN APPOINTMENT C
      ON B.DR_ID = C.MDDR_ID
      WHERE TO_CHAR(C.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
      AND C.MCDP_CD = 'CS'
      AND C.APNT_CNCL_YN = 'N') BC
JOIN PATIENT A
ON A.PT_NO = BC.PT_NO
ORDER BY BC.APNT_YMD ASC;
