최솟값 구하기
동물 보호소에 가장 먼저 들어온 동물은 언제 들어왔는지 조회하는 SQL 문을 작성해주세요.

-- MYSQL
SELECT DATETIME AS "시간"
FROM ANIMAL_INS 
ORDER BY DATETIME ASC
LIMIT 1;

-- ORACLE
SELECT DATETIME AS "시간"
FROM ANIMAL_INS 
ORDER BY DATETIME ASC
FETCH FIRST 1 ROWS ONLY;
