조건에 맞는 사용자와 총 거래금액 조회하기
USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.

-- MYSQL, ORACLE
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER A 
JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
     FROM USED_GOODS_BOARD
     WHERE STATUS = 'DONE'
     GROUP BY WRITER_ID) B
ON WRITER_ID = USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;
