-- 새로운 테이블을 만든다
EX1)
INSERT ALL
INTO IDOL_NAME VALUES (MEMBER_NAME, REAL_NAME)
INTO IDOL_BIRTHDAY VALUES (MEMBER_NAME, BIRTHDAY)
SELECT * FROM IDOL_MEMBER WHERE GROUP_NAME = 'BTS';

SELECT * FROM IDOL_NAME;
SELECT * FROM IDOL_BIRTHDAY;

EX2-1)
INSERT ALL
WHEN LENGTH(GROUP_NAME) < 4 THEN INTO IDOL_NAME VALUES (MEMBER_NAME, REAL_NAME)
WHEN LENGTH(GROUP_NAME) < 5 THEN INTO IDOL_BIRTHDAY VALUES (MEMBER_NAME, BIRTHDAY)
ELSE INTO IDOL_SNS VALUES (MEMBER_NAME, SNS_INFO)
SELECT * FROM IDOL_MEMBER;

SELECT * FROM IDOL_NAME;
-- 결과 : BTS
SELECT * FROM IDOL_BIRTHDAY;
-- 결과 : BTS + 트와이스
SELECT * FROM IDOL_SNS;
-- 결과 : 여자아이들 
